//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InitialProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InitialProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted tours:.
        /// </summary>
        internal static string AcceptedTours_ {
            get {
                return ResourceManager.GetString("AcceptedTours:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add images:.
        /// </summary>
        internal static string AddImages_ {
            get {
                return ResourceManager.GetString("AddImages:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply filters.
        /// </summary>
        internal static string ApplyFilters {
            get {
                return ResourceManager.GetString("ApplyFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance confirmation.
        /// </summary>
        internal static string AttendanceConfirmation {
            get {
                return ResourceManager.GetString("AttendanceConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average guest number:.
        /// </summary>
        internal static string AverageGuestNumber_ {
            get {
                return ResourceManager.GetString("AverageGuestNumber:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        internal static string City_ {
            get {
                return ResourceManager.GetString("City:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment:.
        /// </summary>
        internal static string Comment_ {
            get {
                return ResourceManager.GetString("Comment:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex.
        /// </summary>
        internal static string Complex {
            get {
                return ResourceManager.GetString("Complex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex tour review.
        /// </summary>
        internal static string ComplexTourReview {
            get {
                return ResourceManager.GetString("ComplexTourReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        internal static string Country_ {
            get {
                return ResourceManager.GetString("Country:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create request.
        /// </summary>
        internal static string CreateTourRequest {
            get {
                return ResourceManager.GetString("CreateTourRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creatingc omplex request.
        /// </summary>
        internal static string CreatingComplexRequest {
            get {
                return ResourceManager.GetString("CreatingComplexRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create request for complex tour.
        /// </summary>
        internal static string CreatingRequestForComplexTour {
            get {
                return ResourceManager.GetString("CreatingRequestForComplexTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating request for simple tour.
        /// </summary>
        internal static string CreatingRequestForSimpleTour {
            get {
                return ResourceManager.GetString("CreatingRequestForSimpleTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating simple tour request.
        /// </summary>
        internal static string CreatingSimpleTourRequest {
            get {
                return ResourceManager.GetString("CreatingSimpleTourRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time.
        /// </summary>
        internal static string DateAndTime {
            get {
                return ResourceManager.GetString("DateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date from.
        /// </summary>
        internal static string DateFrom {
            get {
                return ResourceManager.GetString("DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date from:.
        /// </summary>
        internal static string DateFrom_ {
            get {
                return ResourceManager.GetString("DateFrom:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date to.
        /// </summary>
        internal static string DateTo {
            get {
                return ResourceManager.GetString("DateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date to:.
        /// </summary>
        internal static string DateTo_ {
            get {
                return ResourceManager.GetString("DateTo:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string Description_ {
            get {
                return ResourceManager.GetString("Description:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration from.
        /// </summary>
        internal static string DurationFrom {
            get {
                return ResourceManager.GetString("DurationFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration to.
        /// </summary>
        internal static string DurationTo {
            get {
                return ResourceManager.GetString("DurationTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished tours.
        /// </summary>
        internal static string FinishedTours {
            get {
                return ResourceManager.GetString("FinishedTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish date and time.
        /// </summary>
        internal static string FinishingDateAndTime {
            get {
                return ResourceManager.GetString("FinishingDateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest number.
        /// </summary>
        internal static string GuestNumber {
            get {
                return ResourceManager.GetString("GuestNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest number:.
        /// </summary>
        internal static string GuestNumber_ {
            get {
                return ResourceManager.GetString("GuestNumber:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide knowledge:.
        /// </summary>
        internal static string GuideKnowledge_ {
            get {
                return ResourceManager.GetString("GuideKnowledge:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide language:.
        /// </summary>
        internal static string GuideLanguage_ {
            get {
                return ResourceManager.GetString("GuideLanguage:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input number of guest for reservation.
        /// </summary>
        internal static string InputGuestNumberForReservation {
            get {
                return ResourceManager.GetString("InputGuestNumberForReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string Language_ {
            get {
                return ResourceManager.GetString("Language:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last minute.
        /// </summary>
        internal static string LastMinutTours {
            get {
                return ResourceManager.GetString("LastMinutTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        internal static string PeopleNumber {
            get {
                return ResourceManager.GetString("PeopleNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        internal static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate current tour.
        /// </summary>
        internal static string RateCurrentTour {
            get {
                return ResourceManager.GetString("RateCurrentTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        internal static string RateTour {
            get {
                return ResourceManager.GetString("RateTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        internal static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining people number.
        /// </summary>
        internal static string RemainingPeopleNumber {
            get {
                return ResourceManager.GetString("RemainingPeopleNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested tours.
        /// </summary>
        internal static string RequestedTours {
            get {
                return ResourceManager.GetString("RequestedTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve.
        /// </summary>
        internal static string Reserve {
            get {
                return ResourceManager.GetString("Reserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved tours.
        /// </summary>
        internal static string ReservedTours {
            get {
                return ResourceManager.GetString("ReservedTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;!-- 
        ///    Microsoft ResX Schema 
        ///    
        ///    Version 2.0
        ///    
        ///    The primary goals of this format is to allow a simple XML format 
        ///    that is mostly human readable. The generation and parsing of the 
        ///    various data types are done through the TypeConverter classes 
        ///    associated with the data types.
        ///    
        ///    Example:
        ///    
        ///    ... ado.net/XML headers &amp; schema ...
        ///    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        ///    &lt;resheader n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Resources_sr_LATN {
            get {
                return ResourceManager.GetString("Resources_sr_LATN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        internal static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale.
        /// </summary>
        internal static string Sale {
            get {
                return ResourceManager.GetString("Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select voucher.
        /// </summary>
        internal static string SelectVoucher {
            get {
                return ResourceManager.GetString("SelectVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple .
        /// </summary>
        internal static string Simple {
            get {
                return ResourceManager.GetString("Simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting date.
        /// </summary>
        internal static string StartingDate {
            get {
                return ResourceManager.GetString("StartingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting date:.
        /// </summary>
        internal static string StartingDate_ {
            get {
                return ResourceManager.GetString("StartingDate:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date and time.
        /// </summary>
        internal static string StartingDateAndTime {
            get {
                return ResourceManager.GetString("StartingDateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View statistic.
        /// </summary>
        internal static string StatisticView {
            get {
                return ResourceManager.GetString("StatisticView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time:.
        /// </summary>
        internal static string Time_ {
            get {
                return ResourceManager.GetString("Time:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour interest:.
        /// </summary>
        internal static string TourInterest_ {
            get {
                return ResourceManager.GetString("TourInterest:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string TourName {
            get {
                return ResourceManager.GetString("TourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour name:.
        /// </summary>
        internal static string TourName_ {
            get {
                return ResourceManager.GetString("TourName:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour notification.
        /// </summary>
        internal static string TourNotification {
            get {
                return ResourceManager.GetString("TourNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating tour.
        /// </summary>
        internal static string TourRating {
            get {
                return ResourceManager.GetString("TourRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tours.
        /// </summary>
        internal static string Tours {
            get {
                return ResourceManager.GetString("Tours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tours statistics.
        /// </summary>
        internal static string ToursStatistic {
            get {
                return ResourceManager.GetString("ToursStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track.
        /// </summary>
        internal static string Track {
            get {
                return ResourceManager.GetString("Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid from.
        /// </summary>
        internal static string ValidFrom {
            get {
                return ResourceManager.GetString("ValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid until.
        /// </summary>
        internal static string ValidUntil {
            get {
                return ResourceManager.GetString("ValidUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vouchers.
        /// </summary>
        internal static string Vouchers {
            get {
                return ResourceManager.GetString("Vouchers", resourceCulture);
            }
        }
    }
}
